[workspace]

members = [
  "server-conf",
  "smtp-pool",
  "pg-pool",
]
resolver = "2"

[workspace.package]
authors = ["Chuma Takahiro <co.chuma@gmail.com>"]
edition = "2024"

[profile.release]
strip = "debuginfo"
