[package]
name = "smtp-pool"
version = "0.1.1"
rust-version = "1.85"
edition.workspace = true
authors.workspace = true

[dependencies]
lettre = { version = "0.11", features = ["smtp-transport", "tokio1", "tokio1-native-tls"] }
log = "0.4"
server-conf = { path = "../server-conf" }
